### ISSUE TITLE
Getting started not working correctly.

### ISSUE THREAD

**Issue by anakinjay** [aurelia/framework#112]
I followed the getting started word for word (unless I missed something).  When I try to test, I get the following error:
```
http://localhost:8083/modules/airbender/aura/dist/animation-main.js 404 (Not Found)
```
I can confirm there is no dist directory.  I tried copying the src to dist and I get this error:
```
Unhandled promise rejection Error: Error instantiating NavBar.
------------------------------------------------
inner error: TypeError: undefined is not a function
    at exports.default (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/npm/babel-runtime@5.1.13/helpers/define-decorated-property-descriptor.js:9:33)
    at new NavBar (http://drupalcon.dd:8083/modules/airbender/aura/dist/nav-bar.js!eval:23:11)
    at Object.construct (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/npm/core-js@0.9.7/modules/es6.reflect.js:47:25)
    at ClassActivator.invoke (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/dependency-injection@0.7.1/metadata.js:183:26)
    at Container.invoke (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:198:35)
    at Array.<anonymous> (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get [as superGet] (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:131:28)
    at Container.elementContainerGet [as get] (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/templating@0.11.2/view-factory.js:27:17)
    at HtmlBehaviorResource.create (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/templating@0.11.2/html-behavior.js:204:76)
    at applyInstructions (http://drupalcon.dd:8083/modules/airbender/aura/jspm_packages/github/aurelia/templating@0.11.2/view-factory.js:79:33) {innerError: TypeError: undefined is not a function, stack: (...), message: "Error instantiating NavBar.↵----------------------…/aurelia/templating@0.11.2/view-factory.js:79:33)"}
```

**Comment by bitamar** [comment]
@anakinjay - Check for errors in the output of ```jspm install -y```. I had a similar problem, because it couldn't connect to github.

**Comment by 4imble** [comment]
I was having this exact problem. 

Try two things:

1) run `jspm cc` to clear the cache and then try `jspm install -y`
2) run `grunt watch` this will create the dist folder.
