### ISSUE TITLE
Error loading bootstrap Datepicker

### ISSUE THREAD

**Issue by mohsin-citiustech** [aurelia/framework#267]
Hi Guys,
here is my DatePicker Code:
import {inject, customElement, bindable } from 'aurelia-framework';
import moment from 'moment';
import {datepicker} from 'bootstrap-datetimepicker';
@inject(Element)
@bindable('value')
export class DatePicker {
    @bindable format = 'yy-mm-dd';
    constructor(element) {
        this.element = element;
    }
    attached() {
        let self = this;
        self.datePicker = $(self.element).find('.datepicker');
        self.datePicker.datepicker({
            format: self.format,
            startDate: '-3d'
        }).on('changeDate', (e) => {
            console.log('date changed', e.date);
            console.log(moment(e.date).format("YY-MM-DD"));
            self.value = moment(e.date).format("YY-MM-DD");
        });
    }
}

datepicker.html
    input class="datepicker" data-provide="datepicker" value.bind="value"

Config.js
System.config({
    baseURL: "/",
    defaultJSExtensions: true,
    transpiler: "typescript",
    paths: {
       "*": "/*",
        "npm:*": "jspm_packages/npm/*",
        "github:*": "jspm_packages/github/*"
    },
    map: {
        "core-js": "npm:core-js@1.2.6",
        "process": "npm:process@0.11.2",
        "moment": "npm:moment@2.10.6",
        "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
        "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
        "aurelia-framework": "github:aurelia/framework@0.8.8",
        "aurelia-http-client": "github:aurelia/http-client@0.5.5",
        "aurelia-router": "github:aurelia/router@0.5.8",
        "bootstrap": "github:twbs/bootstrap@3.3.2",
        "bootstrap-datepicker": "npm:bootstrap-datepicker@1.5.0",
        "font-awesome": "npm:font-awesome@4.3.0",
        "jquery": "github:components/jquery@2.1.4",
        
        "typescript": "npm:typescript@1.7.3",
        "github:aurelia/binding@0.3.7": {
            "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
            "aurelia-metadata": "github:aurelia/metadata@0.3.3",
            "aurelia-task-queue": "github:aurelia/task-queue@0.2.5"
        },
        "github:aurelia/dependency-injection@0.4.5": {
            "aurelia-metadata": "github:aurelia/metadata@0.3.3",
            "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/framework@0.8.8": {
            "aurelia-binding": "github:aurelia/binding@0.3.7",
            "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
            "aurelia-loader": "github:aurelia/loader@0.3.5",
            "aurelia-logging": "github:aurelia/logging@0.2.5",
            "aurelia-metadata": "github:aurelia/metadata@0.3.3",
            "aurelia-task-queue": "github:aurelia/task-queue@0.2.5",
            "aurelia-templating": "github:aurelia/templating@0.8.14"
        },
        "github:aurelia/http-client@0.5.5": {
            "aurelia-path": "github:aurelia/path@0.4.5",
            "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/loader@0.3.5": {
            "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
            "core-js": "npm:core-js@0.4.10",
            "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.5.5"
        },
        "github:aurelia/router@0.5.8": {
            "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
            "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.2.4",
            "aurelia-history": "github:aurelia/history@0.2.4",
            "aurelia-path": "github:aurelia/path@0.4.5",
            "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.2.4",
            "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/templating@0.8.14": {
            "aurelia-binding": "github:aurelia/binding@0.3.7",
            "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
            "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
            "aurelia-loader": "github:aurelia/loader@0.3.5",
            "aurelia-logging": "github:aurelia/logging@0.2.5",
            "aurelia-metadata": "github:aurelia/metadata@0.3.3",
            "aurelia-path": "github:aurelia/path@0.4.5",
            "aurelia-task-queue": "github:aurelia/task-queue@0.2.5",
            "core-js": "npm:core-js@0.4.10"
        },
        "github:jspm/nodelibs-assert@0.1.0": {
            "assert": "npm:assert@1.3.0"
        },
        "github:jspm/nodelibs-path@0.1.0": {
            "path-browserify": "npm:path-browserify@0.0.0"
        },
        "github:jspm/nodelibs-process@0.1.2": {
            "process": "npm:process@0.11.2"
        },
        "github:jspm/nodelibs-util@0.1.0": {
            "util": "npm:util@0.10.3"
        },
        "npm:assert@1.3.0": {
            "util": "npm:util@0.10.3"
        },
        "npm:aurelia-binding@1.0.0-beta.1.0.1": {
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-bootstrapper@1.0.0-beta.1": {
            "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
            "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.2",
            "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
            "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1",
            "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.1",
            "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1",
            "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
            "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
            "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1",
            "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.1",
            "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-dependency-injection@1.0.0-beta.1": {
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-event-aggregator@1.0.0-beta.1": {
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1"
        },
        "npm:aurelia-framework@1.0.0-beta.1.0.2": {
            "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
            "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
            "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
            "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-history-browser@1.0.0-beta.1": {
            "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-loader-default@1.0.0-beta.1.0.1": {
            "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
        },
        "npm:aurelia-loader@1.0.0-beta.1": {
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1"
        },
        "npm:aurelia-logging-console@1.0.0-beta.1": {
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
        },
        "npm:aurelia-metadata@1.0.0-beta.1": {
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-pal-browser@1.0.0-beta.1": {
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
        },
        "npm:aurelia-route-recognizer@1.0.0-beta.1": {
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-router@1.0.0-beta.1": {
            "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
            "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1",
            "aurelia-history": "npm:aurelia-history@1.0.0-beta.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-task-queue@1.0.0-beta.1": {
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1"
        },
        "npm:aurelia-templating-binding@1.0.0-beta.1": {
            "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
        },
        "npm:aurelia-templating-resources@1.0.0-beta.1.0.1": {
            "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
            "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
            "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
            "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },
        "npm:aurelia-templating-router@1.0.0-beta.1.0.1": {
            "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
            "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1"
        },
        "npm:aurelia-templating@1.0.0-beta.1": {
            "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.0.1",
            "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1",
            "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1",
            "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1",
            "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1",
            "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1",
            "aurelia-path": "npm:aurelia-path@1.0.0-beta.1",
            "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1",
            "core-js": "npm:core-js@1.2.6"
        },

        "npm:inherits@2.0.1": {
            "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:moment@2.10.6": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:path-browserify@0.0.0": {
            "process": "github:jspm/nodelibs-process@0.1.2"
        },
        "npm:util@0.10.3": {
            "inherits": "npm:inherits@2.0.1",
            "process": "github:jspm/nodelibs-process@0.1.2"
        }
    }
});

Issue: Datepicker is not loading and in console I am getting following error.

ERROR [app-router] Error: XHR error (404 Not Found) loading http://localhost:11228/jspm_packages/npm/moment@2.10.6.js
	Error loading http://localhost:11228/jspm_packages/npm/moment@2.10.6.js as "moment" from http://localhost:11228/views/components/DatePicker.js
    at o (http://localhost:11228/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:11228/jspm_packages/system.js:4:13219)

**Comment by mohsin-citiustech** [comment]
Issue resolved, It was config issue.
