### ISSUE TITLE
Hub script error

### ISSUE THREAD

**Issue by JamesCrann** [aurelia/framework#509]
**I'm submitting a bug report**

Script Error in http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-value-converters/3

```
Unhandled rejection TypeError: moment is not a function
    at DateFormatValueConverter.toView (https://cdn.rawgit.com/aurelia/binding/1.0.1/doc/example-dist/binding-value-converters/simple-converter/date-format.js:40:14)
    at t.e.ValueConverter.t.evaluate (http://aurelia.io/scripts/vendor-bundle.js:6:17875)
    at e.ChildInterpolationBinding.e.bind (http://aurelia.io/scripts/vendor-bundle.js:14:15995)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:4424)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:26172)
    at e.Controller.e.automate (http://aurelia.io/scripts/vendor-bundle.js:13:25432)
    at http://aurelia.io/scripts/vendor-bundle.js:14:6701

```

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Browser:**
  Chrome  51.0.2704.103 m

Confirmed also an issue on Android Chrome

**Comment by t03apt** [comment]
Another page is broken now.
See: http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection

Error:
Unhandled rejection TypeError: Cannot read property 'code' of undefined
    at e.CodeListing.e.select (http://aurelia.io/scripts/app-bundle.js:3:22729)
    at e.CodeListing.e.selectSourceForLanguage (http://aurelia.io/scripts/app-bundle.js:3:22627)
    at e.CodeListing.e.bind (http://aurelia.io/scripts/app-bundle.js:3:21584)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:7845)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:29578)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:7995)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:29578)
    at e.Controller.e.automate (http://aurelia.io/scripts/vendor-bundle.js:13:28838)
    at http://aurelia.io/scripts/vendor-bundle.js:14:10133

**Comment by Gheoan** [comment]
@t03apt That is another issue. Already reported here: https://github.com/aurelia/templating/issues/536.

**Comment by Alexander-Taran** [comment]
Who's issue is this?
Hub's
Who is Hub?
Hub's dead, baby.
Hub's dead

**Comment by EisenbergEffect** [comment]
Re-wrote the entire site.
