### ISSUE TITLE
--watch doesn't work

### ISSUE THREAD

**Issue by jfbaquerocelis** [aurelia/framework#520]
**I'm submitting a bug report**

* **Operating System:**
Linux (Ubuntu 16.04 LTS)

* **Node Version:**
4.4.7

* **NPM Version:**
2.15.8

* **Language:**
ESNext

Hi :smiley:. I had installed Aurelia and I started a new project with `au new [project_name]` and it's ok. But when I excecute `au run --watch` I see this error:

```
Application Available At: http://localhost:9000
BrowserSync Available At: http://localhost:3001
Starting 'watch'...
{ uid: 12,
  name: 'watch',
  branch: false,
  error: 
   { [Error: watch src ENOSPC]
     code: 'ENOSPC',
     errno: 'ENOSPC',
     syscall: 'watch src',
     filename: 'src',
     domainEmitter: 
      FSWatcher {
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _watched: [Object],
        _closers: {},
        _ignoredPaths: {},
        closed: false,
        _throttled: {},
        _symlinkPaths: {},
        enableBinaryInterval: true,
        _pendingUnlinks: {},
        _isntIgnored: [Function: bound ],
        _emitReady: [Function: bound ],
        options: [Object],
        _userIgnored: [Function: bound ],
        _readyCount: 1 },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 0, 10953994 ],
  time: 1470327940586 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: watch src ENOSPC]
     code: 'ENOSPC',
     errno: 'ENOSPC',
     syscall: 'watch src',
     filename: 'src',
     domainEmitter: 
      FSWatcher {
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _watched: [Object],
        _closers: {},
        _ignoredPaths: {},
        closed: false,
        _throttled: {},
        _symlinkPaths: {},
        enableBinaryInterval: true,
        _pendingUnlinks: {},
        _isntIgnored: [Function: bound ],
        _emitReady: [Function: bound ],
        options: [Object],
        _userIgnored: [Function: bound ],
        _readyCount: 1 },
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: false },
  duration: [ 3, 956023456 ],
  time: 1470327940599 }
{ [Error: watch src ENOSPC]
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch src',
  filename: 'src',
  domainEmitter: 
   FSWatcher {
     domain: 
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     _events: { change: [Object], unlink: [Object], add: [Object] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _watched: 
      { '/home/nover/Documentos/Projects/Aurelia.io/store': [Object],
        '/home/nover/Documentos/Projects/Aurelia.io/store/src': [Object],
        '/home/nover/Documentos/Projects/Aurelia.io/store/src/**/*.js': [Object] },
     _closers: {},
     _ignoredPaths: {},
     closed: false,
     _throttled: {},
     _symlinkPaths: {},
     enableBinaryInterval: true,
     _pendingUnlinks: {},
     _isntIgnored: [Function: bound ],
     _emitReady: [Function: bound ],
     options: 
      { ignoreInitial: true,
        delay: 200,
        queue: true,
        persistent: true,
        ignorePermissionErrors: false,
        interval: 100,
        binaryInterval: 300,
        useFsEvents: false,
        usePolling: false,
        atomic: true,
        followSymlinks: true,
        awaitWriteFinish: false },
     _userIgnored: [Function: bound ],
     _readyCount: 1 },
  domain: 
   Domain {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     members: [] },
  domainThrown: false }
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch src ENOSPC
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/nover/Documentos/Projects/Aurelia.io/store/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

What is happen? Thanks :relaxed:

**Comment by EisenbergEffect** [comment]
Search "ENOSPC" and you will find your answer.

**Comment by AshleyGrant** [comment]
Also, you need to upgrade to a `3.x` version of npm.

**Comment by jfbaquerocelis** [comment]
@EisenbergEffect @AshleyGrant Thanks for all :+1: 

I put this command in console:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

and already it is running!

Regards!!
