### ISSUE TITLE
Doc HUB not working properly, when blocking Google Analytics

### ISSUE THREAD

**Issue by brylie** [aurelia/framework#707]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Operating System:**
Linux: Ubuntu 16.04

* **Browser:**
Firefox 50.1.0

**Current behavior:**
The Docs HUB pages do not render when navigating via the sidebar:
![peek 2017-02-03 13-40](https://cloud.githubusercontent.com/assets/17307/22590136/6faccf9e-ea16-11e6-9d8f-8dbc7d221e7e.gif)

**Expected/desired behavior:**
* **What is the expected behavior?**
I expect for Docs HUB documentation to work in Firefox.

* **What is the motivation / use case for changing the behavior?**
In order to learn Aurelia, I need to be able to read the documentation. Also, since Firefox is a very popular browser, it is important to make sure things work with recent versions of FF.

**Comment by brylie** [comment]
Allowing Google Analytics for the Doc HUB site fixes the issue. However, it might be worth the effort to make the Doc HUB site work without tracking software.

**Comment by TomFoyster** [comment]
I'm having the same issue on Chrome, though accompanied with the following Warning/Exceptions in the console;

```
Unhandled rejection TypeError: Cannot read property 'content' of undefined
    at e._subsume (http://aurelia.io/scripts/app-bundle.js:1:6680)
    at http://aurelia.io/scripts/app-bundle.js:1:6136
From previous event:
    at e.AureliaDoc.e._loadTranslation (http://aurelia.io/scripts/app-bundle.js:1:6095)
    at e.AureliaDoc.e.getTranslation (http://aurelia.io/scripts/app-bundle.js:1:5882)
    at e.ProductVersion.e.getArticle (http://aurelia.io/scripts/app-bundle.js:2:23689)
    at http://aurelia.io/scripts/app-bundle.js:2:10180
From previous event:
    at e.Article.e.loadDocument (http://aurelia.io/scripts/app-bundle.js:2:10154)
    at e.Article.e.load (http://aurelia.io/scripts/app-bundle.js:2:10431)
    at e.ArticleRoute.e.activate (http://aurelia.io/scripts/app-bundle.js:3:26387)
    at http://aurelia.io/scripts/vendor-bundle.js:11:15912
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15995)
    at k (http://aurelia.io/scripts/vendor-bundle.js:11:16139)
    at e.ActivateNextStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:1054)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15210)
    at w (http://aurelia.io/scripts/vendor-bundle.js:11:15245)
    at e.DeactivatePreviousStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:930)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:16099)
    at k (http://aurelia.io/scripts/vendor-bundle.js:11:16139)
    at e.CanActivateNextStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:807)
From previous event:
    at e.LoadRouteStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:1747)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15210)
    at w (http://aurelia.io/scripts/vendor-bundle.js:11:15245)
    at e.CanDeactivatePreviousStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:680)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at http://aurelia.io/scripts/vendor-bundle.js:11:27165
From previous event:
    at e.BuildNavigationPlanStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:11:27132)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at e.Pipeline.e.run (http://aurelia.io/scripts/vendor-bundle.js:11:21160)
    at http://aurelia.io/scripts/vendor-bundle.js:12:5490
From previous event:
    at t.e.AppRouter.t._dequeueInstruction (http://aurelia.io/scripts/vendor-bundle.js:12:4937)
    at t.e.AppRouter.t.activate (http://aurelia.io/scripts/vendor-bundle.js:12:4553)
    at http://aurelia.io/scripts/vendor-bundle.js:12:4162
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:12:4144
    at http://aurelia.io/scripts/vendor-bundle.js:12:4181
    at t.e.AppRouter.t.registerViewPort (http://aurelia.io/scripts/vendor-bundle.js:12:4269)
    at new e (http://aurelia.io/scripts/vendor-bundle.js:19:23148)
    at Object.f (http://aurelia.io/scripts/vendor-bundle.js:5:23269)
    at e.InvocationHandler.e.invoke (http://aurelia.io/scripts/vendor-bundle.js:5:27909)
    at e.Container.e.invoke (http://aurelia.io/scripts/vendor-bundle.js:5:31341)
    at e.get (http://aurelia.io/scripts/vendor-bundle.js:13:14993)
    at e.Container.e.get (http://aurelia.io/scripts/vendor-bundle.js:5:30620)
    at e.g [as get] (http://aurelia.io/scripts/vendor-bundle.js:12:9444)
    at e.HtmlBehaviorResource.e.create (http://aurelia.io/scripts/vendor-bundle.js:14:5908)
    at w (http://aurelia.io/scripts/vendor-bundle.js:12:10692)
    at e.ViewFactory.e.create (http://aurelia.io/scripts/vendor-bundle.js:13:16960)
    at e.HtmlBehaviorResource.e.create (http://aurelia.io/scripts/vendor-bundle.js:14:6109)
    at http://aurelia.io/scripts/vendor-bundle.js:14:10699
From previous event:
    at e.CompositionEngine.e.createController (http://aurelia.io/scripts/vendor-bundle.js:14:10673)
    at e.CompositionEngine.e._createControllerAndSwap (http://aurelia.io/scripts/vendor-bundle.js:14:10087)
    at e.CompositionEngine.e.compose (http://aurelia.io/scripts/vendor-bundle.js:14:11774)
    at e.TemplatingEngine.e.compose (http://aurelia.io/scripts/vendor-bundle.js:14:13167)
    at e.Aurelia.e.setRoot (http://aurelia.io/scripts/vendor-bundle.js:9:19072)
    at http://aurelia.io/scripts/app-bundle.js:1:4215
From previous event:
    at Object.r [as configure] (http://aurelia.io/scripts/app-bundle.js:1:4189)
    at http://aurelia.io/scripts/vendor-bundle.js:9:7683
From previous event:
    at u (http://aurelia.io/scripts/vendor-bundle.js:9:7566)
    at a (http://aurelia.io/scripts/vendor-bundle.js:9:7465)
    at http://aurelia.io/scripts/vendor-bundle.js:9:8012
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:9:7965
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:9:7936
From previous event:
    at l (http://aurelia.io/scripts/vendor-bundle.js:9:7828)
    at Object.<anonymous> (http://aurelia.io/scripts/vendor-bundle.js:9:8262)
    at Object.execCb (http://aurelia.io/scripts/vendor-bundle.js:5:9133)
    at w.check (http://aurelia.io/scripts/vendor-bundle.js:5:3320)
    at w.enable (http://aurelia.io/scripts/vendor-bundle.js:5:5891)
    at Object.enable (http://aurelia.io/scripts/vendor-bundle.js:5:8255)
    at w.<anonymous> (http://aurelia.io/scripts/vendor-bundle.js:5:5763)
    at http://aurelia.io/scripts/vendor-bundle.js:4:29902
    at y (http://aurelia.io/scripts/vendor-bundle.js:4:29463)
    at w.enable (http://aurelia.io/scripts/vendor-bundle.js:5:5291)
    at w.init (http://aurelia.io/scripts/vendor-bundle.js:5:2449)
    at http://aurelia.io/scripts/vendor-bundle.js:5:7627
```

```
Warning: a promise was rejected with a non-error: [object Object]
    at XMLHttpRequest.r.onerror (http://aurelia.io/scripts/vendor-bundle.js:9:29234)
From previous event:
    at e.RequestMessageProcessor.e.process (http://aurelia.io/scripts/vendor-bundle.js:9:28974)
    at http://aurelia.io/scripts/vendor-bundle.js:10:2843
From previous event:
    at e.HttpClient.e.send (http://aurelia.io/scripts/vendor-bundle.js:10:2778)
    at e.RequestBuilder.e.send (http://aurelia.io/scripts/vendor-bundle.js:10:2029)
    at e.Server.e.loadArticleTranslation (http://aurelia.io/scripts/app-bundle.js:1:19519)
    at e.AureliaDoc.e._loadTranslation (http://aurelia.io/scripts/app-bundle.js:1:6069)
    at e.AureliaDoc.e.getTranslation (http://aurelia.io/scripts/app-bundle.js:1:5882)
    at e.ProductVersion.e.getArticle (http://aurelia.io/scripts/app-bundle.js:2:23689)
    at http://aurelia.io/scripts/app-bundle.js:2:10180
From previous event:
    at e.Article.e.loadDocument (http://aurelia.io/scripts/app-bundle.js:2:10154)
    at e.Article.e.load (http://aurelia.io/scripts/app-bundle.js:2:10431)
    at e.ArticleRoute.e.activate (http://aurelia.io/scripts/app-bundle.js:3:26387)
    at http://aurelia.io/scripts/vendor-bundle.js:11:15912
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15995)
    at k (http://aurelia.io/scripts/vendor-bundle.js:11:16139)
    at e.ActivateNextStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:1054)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15210)
    at w (http://aurelia.io/scripts/vendor-bundle.js:11:15245)
    at e.DeactivatePreviousStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:930)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:16099)
    at k (http://aurelia.io/scripts/vendor-bundle.js:11:16139)
    at e.CanActivateNextStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:807)
From previous event:
    at e.LoadRouteStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:1747)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at o (http://aurelia.io/scripts/vendor-bundle.js:11:15210)
    at w (http://aurelia.io/scripts/vendor-bundle.js:11:15245)
    at e.CanDeactivatePreviousStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:12:680)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at http://aurelia.io/scripts/vendor-bundle.js:11:27165
From previous event:
    at e.BuildNavigationPlanStep.e.run (http://aurelia.io/scripts/vendor-bundle.js:11:27132)
    at t (http://aurelia.io/scripts/vendor-bundle.js:11:21017)
    at e.Pipeline.e.run (http://aurelia.io/scripts/vendor-bundle.js:11:21160)
    at http://aurelia.io/scripts/vendor-bundle.js:12:5490
From previous event:
    at t.e.AppRouter.t._dequeueInstruction (http://aurelia.io/scripts/vendor-bundle.js:12:4937)
    at t.e.AppRouter.t.activate (http://aurelia.io/scripts/vendor-bundle.js:12:4553)
    at http://aurelia.io/scripts/vendor-bundle.js:12:4162
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:12:4144
    at http://aurelia.io/scripts/vendor-bundle.js:12:4181
    at t.e.AppRouter.t.registerViewPort (http://aurelia.io/scripts/vendor-bundle.js:12:4269)
    at new e (http://aurelia.io/scripts/vendor-bundle.js:19:23148)
    at Object.f (http://aurelia.io/scripts/vendor-bundle.js:5:23269)
    at e.InvocationHandler.e.invoke (http://aurelia.io/scripts/vendor-bundle.js:5:27909)
    at e.Container.e.invoke (http://aurelia.io/scripts/vendor-bundle.js:5:31341)
    at e.get (http://aurelia.io/scripts/vendor-bundle.js:13:14993)
    at e.Container.e.get (http://aurelia.io/scripts/vendor-bundle.js:5:30620)
    at e.g [as get] (http://aurelia.io/scripts/vendor-bundle.js:12:9444)
    at e.HtmlBehaviorResource.e.create (http://aurelia.io/scripts/vendor-bundle.js:14:5908)
    at w (http://aurelia.io/scripts/vendor-bundle.js:12:10692)
    at e.ViewFactory.e.create (http://aurelia.io/scripts/vendor-bundle.js:13:16960)
    at e.HtmlBehaviorResource.e.create (http://aurelia.io/scripts/vendor-bundle.js:14:6109)
    at http://aurelia.io/scripts/vendor-bundle.js:14:10699
From previous event:
    at e.CompositionEngine.e.createController (http://aurelia.io/scripts/vendor-bundle.js:14:10673)
    at e.CompositionEngine.e._createControllerAndSwap (http://aurelia.io/scripts/vendor-bundle.js:14:10087)
    at e.CompositionEngine.e.compose (http://aurelia.io/scripts/vendor-bundle.js:14:11774)
    at e.TemplatingEngine.e.compose (http://aurelia.io/scripts/vendor-bundle.js:14:13167)
    at e.Aurelia.e.setRoot (http://aurelia.io/scripts/vendor-bundle.js:9:19072)
    at http://aurelia.io/scripts/app-bundle.js:1:4215
From previous event:
    at Object.r [as configure] (http://aurelia.io/scripts/app-bundle.js:1:4189)
    at http://aurelia.io/scripts/vendor-bundle.js:9:7683
From previous event:
    at u (http://aurelia.io/scripts/vendor-bundle.js:9:7566)
    at a (http://aurelia.io/scripts/vendor-bundle.js:9:7465)
    at http://aurelia.io/scripts/vendor-bundle.js:9:8012
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:9:7965
From previous event:
    at http://aurelia.io/scripts/vendor-bundle.js:9:7936
From previous event:
    at l (http://aurelia.io/scripts/vendor-bundle.js:9:7828)
    at Object.<anonymous> (http://aurelia.io/scripts/vendor-bundle.js:9:8262)
    at Object.execCb (http://aurelia.io/scripts/vendor-bundle.js:5:9133)
    at w.check (http://aurelia.io/scripts/vendor-bundle.js:5:3320)
    at w.enable (http://aurelia.io/scripts/vendor-bundle.js:5:5891)
    at Object.enable (http://aurelia.io/scripts/vendor-bundle.js:5:8255)
    at w.<anonymous> (http://aurelia.io/scripts/vendor-bundle.js:5:5763)
    at http://aurelia.io/scripts/vendor-bundle.js:4:29902
    at y (http://aurelia.io/scripts/vendor-bundle.js:4:29463)
    at w.enable (http://aurelia.io/scripts/vendor-bundle.js:5:5291)
    at w.init (http://aurelia.io/scripts/vendor-bundle.js:5:2449)
    at http://aurelia.io/scripts/vendor-bundle.js:5:7627
```

**Comment by TomFoyster** [comment]
I've discovered this is a local issue related to our proxy :(

**Comment by brylie** [comment]
Cool. For what it's worth, this problem seems to have been resolved recently.

**Comment by Alexander-Taran** [comment]
Can be closed
