### ISSUE TITLE
Systemjs fails to import mqtt

### ISSUE THREAD

**Issue by Florimond** [aurelia/framework#727]
**I'm submitting a bug report**

* **Library Version:**
1.0.8

* **Operating System:**
Windows 10

* **Node Version:**
6.9.5

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.19.46

* **Browser:**
all

**Current behavior:**
 I try to import mqtt by adding the following line in the *app.js*.

```
import mqtt from 'mqtt';
```

Which results in the following error :

```
Error: (SystemJS) Cannot read property 'prototype' of undefined
	TypeError: Cannot read property 'prototype' of undefined
	    at inherits (http://localhost:9000/jspm_packages/npm/inherits@2.0.3/inherits_browser.js:6:45)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:24:1)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:26:4)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:27:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/ws.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/mqtt.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0.js
	Error loading http://localhost:9000/app.js
	    at inherits (http://localhost:9000/jspm_packages/npm/inherits@2.0.3/inherits_browser.js:6:45)
	    at Object.eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:24:1)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:26:4)
	    at eval (http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js:27:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/server.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/websocket-stream@3.3.3.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/ws.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/lib/connect/index.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0/mqtt.js
	Evaluating http://localhost:9000/jspm_packages/npm/mqtt@2.4.0.js
	Error loading http://localhost:9000/app.js
  ```
![alt](https://raw.githubusercontent.com/Florimond/aurelia-mqtt-issue/master/inherits%20websocketserver.png)

![alt](https://github.com/Florimond/aurelia-mqtt-issue/blob/master/require%20ws-fallback.png?raw=true)

**Steps to reproduce the issue**
Here is my repo demonstrating the issue : https://github.com/Florimond/aurelia-mqtt-issue/

Create a minimalist aurelia install based on instructions from [How to set up minimal Aurelia project from scratch](http://stackoverflow.com/questions/32080221/how-to-set-up-minimal-aurelia-project-from-scratch)

Then install mqtt with :

```
jspm install npm:mqtt
```

Add the following line in the *app.js*.
```
import mqtt from 'mqtt';
```

**Comment by AshleyGrant** [comment]
This is a SystemJS issue, please submit the issue to https://github.com/systemjs/systemjs/issues
