### ISSUE TITLE
installing and using i18n

### ISSUE THREAD

**Issue by stuartbloom** [aurelia/framework#729]
Hi there

I have the typescript skeleton application that I am staring to make changes to to get an idea of how it all fits together.

I have performed the jspm installation for i18n as per [here](http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/1).

Unfortuately, when I add
`import {I18N} from 'aurelia-i18n';
import Backend from 'i18next-xhr-backend';
`
into my main.ts file i get an error stating that neither package can be found.

Any ideas as to what I am doing wrong?

Thanks in advance

**Comment by cluka** [comment]
Have you installed the correct typings?
You can read more here: http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/4

**Comment by stuartbloom** [comment]
clika, hanging my head in shame, thank you, however I am not out of the woods yet.  I am nw getting this error: 
Error: typings\modules\aurelia-i18n\index.d.ts(4,8): error TS1192: Module ''i18next'' has no default export.

Thanks again

**Comment by zewa666** [comment]
@stuartbloom if you continue reading the i18n hub section about Typescript you'll find the info about allowSyntheticDefaultImports which has to be set in your tsconfig

**Comment by stuartbloom** [comment]
Folks, thank you very much, sorry i didn't continue to the end of the document.

I have everything in place; I think. but when I run the application (the simple one created with the au cli), i get the following issues in the console:
`Unhandled rejection TypeError: Cannot read property 'type' of undefined
    at I18n.use (http://localhost:9001/scripts/vendor-bundle.js:26806:15)
    at http://localhost:9001/scripts/app-bundle.js:43:30
    at registerI18N (http://localhost:9001/scripts/vendor-bundle.js:27010:15)
    at Object.configure (http://localhost:9001/scripts/vendor-bundle.js:27072:28)
    at http://localhost:9001/scripts/vendor-bundle.js:12746:36

From previous event:
    at _loadPlugin (http://localhost:9001/scripts/vendor-bundle.js:12744:42)
    at http://localhost:9001/scripts/vendor-bundle.js:12737:16

From previous event:
    at loadPlugin (http://localhost:9001/scripts/vendor-bundle.js:12736:75)
    at next (http://localhost:9001/scripts/vendor-bundle.js:12998:20)

From previous event:
    at next (http://localhost:9001/scripts/vendor-bundle.js:12998:56)
    at http://localhost:9001/scripts/vendor-bundle.js:13005:16

From previous event:
    at FrameworkConfiguration.apply (http://localhost:9001/scripts/vendor-bundle.js:12990:44)
    at Aurelia.start (http://localhost:9001/scripts/vendor-bundle.js:12606:39)
    at Object.configure (http://localhost:9001/scripts/app-bundle.js:60:17)
    at http://localhost:9001/scripts/vendor-bundle.js:11505:22

From previous event:
    at config (http://localhost:9001/scripts/vendor-bundle.js:11500:48)
    at handleApp (http://localhost:9001/scripts/vendor-bundle.js:11491:12)
    at http://localhost:9001/scripts/vendor-bundle.js:11524:13

From previous event:
    at http://localhost:9001/scripts/vendor-bundle.js:11522:40

From previous event:
    at http://localhost:9001/scripts/vendor-bundle.js:11521:29

From previous event:
    at run (http://localhost:9001/scripts/vendor-bundle.js:11517:26)
    at Object.<anonymous> (http://localhost:9001/scripts/vendor-bundle.js:11544:3)
    at Object.execCb (http://localhost:9001/scripts/vendor-bundle.js:5435:33)
    at Module.check (http://localhost:9001/scripts/vendor-bundle.js:4622:51)
    at Module.enable (http://localhost:9001/scripts/vendor-bundle.js:4915:22)
    at Object.enable (http://localhost:9001/scripts/vendor-bundle.js:5296:39)
    at Module.<anonymous> (http://localhost:9001/scripts/vendor-bundle.js:4900:33)
    at http://localhost:9001/scripts/vendor-bundle.js:3873:23
    at each (http://localhost:9001/scripts/vendor-bundle.js:3798:31)
    at Module.enable (http://localhost:9001/scripts/vendor-bundle.js:4852:17)
    at Module.init (http://localhost:9001/scripts/vendor-bundle.js:4527:26)
    at http://localhost:9001/scripts/vendor-bundle.js:5199:36`

any idea on what I am missing?

Thanks in advance again

**Comment by zewa666** [comment]
@stuartbloom hehe np, enjoy work with the i18n plugin.
