### ISSUE TITLE
aurelia-binding-loader seems to break npm shrinkwrap

### ISSUE THREAD

**Issue by suamikim** [aurelia/framework#738]
**I'm submitting a bug report**

* **Library Version:**
CLI `0.26.1`
Framework `1.1.0`

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.1

* **Browser:**
Chrome 56 but it's not browser related

* **Language:**
TypeScript 2.2.1

**Current behavior:**
Running `npm shrinkwrap` from my project results in the following error which is written to `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 info lifecycle myproject@0.1.0~preshrinkwrap: myproject@0.1.0
5 silly lifecycle myproject@0.1.0~preshrinkwrap: no script for preshrinkwrap, continuing
6 info lifecycle myproject@0.1.0~shrinkwrap: myproject@0.1.0
7 silly lifecycle myproject@0.1.0~shrinkwrap: no script for shrinkwrap, continuing
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack extraneous: aurelia-binding-loader@1.1.0 D:\dev\MyProject\node_modules\aurelia-binding-loader
8 verbose stack     at shrinkwrap_ (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\shrinkwrap.js:128:15)
8 verbose stack     at Array.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8 verbose stack     at LOOP (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at done (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:132:5)
8 verbose stack     at LOOP (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:318:20
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
9 verbose cwd D:\dev\MyProject
10 error Windows_NT 10.0.14393
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
12 error node v6.9.4
13 error npm  v4.1.1
14 error Problems were encountered
14 error Please correct and try again.
14 error extraneous: aurelia-binding-loader@1.1.0 D:\dev\MyProject\node_modules\aurelia-binding-loader
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

Unfortunately I wasn't able to reproduce this using a completely fresh CLI project and don't have the time right now to dig deeper into it to see "what" actually causes this in ma project.

Any ideas on why this could happen? I'd really appreciate if I could use `npm shrinkwrap` in my project.

I've also created [an issue in npms repo](https://github.com/npm/npm/issues/16057) as suggested in the error log.

**Comment by suamikim** [comment]
As suggested in [the issue in npms repo](https://github.com/npm/npm/issues/16057#issuecomment-287108987) a simple `npm prune` fixed it for me.
