### ISSUE TITLE
IE11 unable to get property replaceChild

### ISSUE THREAD

**Issue by TimBailey-pnk** [aurelia/framework#779]
I'm submitting a bug report

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:** 
n/a
* **NPM Version:**
n/a

* **Browser:**
IE 11

* **Language:**
n/a

**Current behavior:**
Get a unhandled rejection in IE11
As per #27, when browsing Aurelia app via IE11 get error below and screen is empty

ie visit http://aurelia.io/hub.html#/doc/index in IE11

```
Unhandled rejection TypeError: Unable to get property 'replaceChild' of undefined or null reference
   at e._DOM.replaceNode (http://aurelia.io/scripts/vendor-bundle.js:11:2401)
   at O (http://aurelia.io/scripts/vendor-bundle.js:12:12171)
   at e.prototype._compileElement (http://aurelia.io/scripts/vendor-bundle.js:13:20231)
   at e.prototype._compileNode (http://aurelia.io/scripts/vendor-bundle.js:13:18059)
   at e.prototype._compileNode (http://aurelia.io/scripts/vendor-bundle.js:13:18541)
   at e.prototype.compile (http://aurelia.io/scripts/vendor-bundle.js:13:17597)
   at Anonymous function (http://aurelia.io/scripts/vendor-bundle.js:13:26061)
   at i (http://aurelia.io/scripts/vendor-bundle.js:2:17240)
   at r.prototype._settlePromiseFromHandler (http://aurelia.io/scripts/vendor-bundle.js:2:5438)
   at r.prototype._settlePromise (http://aurelia.io/scripts/vendor-bundle.js:2:6243)
```

**Expected/desired behavior:**
For it to display correctly

**Comment by EisenbergEffect** [comment]
Can you provide a simplified reproduction that we can use to test this?

**Comment by tulir** [comment]
I started getting this error if I tried to load the page (in IE11) while `au build` was running. Also, refreshing the tab after `au build` had completed didn't fix the error. Only opening a new tab fixed it.

**Comment by Alexander-Taran** [comment]
can't repro

**Comment by EisenbergEffect** [comment]
Closing because either it was fixed or at least it can no longer be reproduced.

**Comment by davismj** [comment]
This seems to be the result of adding a template inside a template, including custom elements. So something like these:

<template slot="name"></template

<template>
  <div if.bind="isTrue"></div>
</tempate>

<template>
  <template repeat.for="i of 10"></template
</template>
