### ISSUE TITLE
useView decorator is unable to find my view

### ISSUE THREAD

**Issue by jdemeuse1204** [aurelia/framework#789]
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.0

* **NPM Version:**
3.10.10

* **Aurelia CLI OR JSPM OR Webpack AND Version**
webpack 2.5.1

* **Browser:**
Chrome 58

* **Language:**
ESNext

**Current behavior:**
Typically when I create my SPA I have views and viewmodels split into their respective folders.  So, under the `src` folder would be `views` and `viewmodels`.  I am trying to upgrade my aurelia app from about 6 months ago using the new skeleton.  When I put the `@useView` decorator on my view models, I get an error saying the module id cannot be found.  For example, I put my app.html in the views folder and my app.js file in the viewmodels folder.  Then the `@useView` decorator was added to the app.js file.

Here are the paths I tried in `@useView`:
1. '../views/app.html'
2. 'views/app.html'
3. 'views/app'
4. PLATFORM.moduleName('../views/app.html')

Each time I get the same error:

```
aurelia-logging-console.js:27 INFO [aurelia] Aurelia Started
bluebird.js:5253 Error: Unable to find module with ID: views/app.html
    at WebpackLoader.<anonymous> (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17357:35)
    at step (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17206:23)
    at Object.next (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17187:53)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17181:71
    at 201.__awaiter (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17177:12)
    at WebpackLoader.201.WebpackLoader._import (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17322:16)
    at WebpackLoader.<anonymous> (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17422:44)
    at step (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17206:23)
    at Object.next (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17187:53)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17181:71
    at 201.__awaiter (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17177:12)
    at WebpackLoader.201.WebpackLoader.loadModule (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17409:16)
    at WebpackLoader.<anonymous> (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17452:55)
From previous event:
    at 201.__awaiter (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17177:12)
    at WebpackLoader.201.WebpackLoader.loadModule (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17409:16)
    at WebpackLoader.201.WebpackLoader.loadTemplate (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17440:21)
    at ensureRegistryEntry (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:32642:17)
    at ViewEngine.loadViewFactory (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:32710:12)
    at RelativeViewStrategy.loadViewFactory (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:30080:23)
    at HtmlBehaviorResource.load (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:33482:27)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:34041:16
From previous event:
    at CompositionEngine.createController (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:34029:69)
    at CompositionEngine._createControllerAndSwap (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:34004:17)
    at CompositionEngine.compose (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:34090:19)
    at TemplatingEngine.compose (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:34354:36)
    at Aurelia.setRoot (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:44118:19)
    at Object._callee$ (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48779:26)
    at tryCatch (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:22860:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:23098:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:22912:21)
    at step (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48738:191)
From previous event:
    at step (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48738:330)
    at _next (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48738:379)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48738:447
From previous event:
    at Object.<anonymous> (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48738:99)
    at Object.configure (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:48789:17)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17113:27
From previous event:
    at config (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17108:54)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17144:12
From previous event:
    at bootstrap (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17143:24)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17130:7
From previous event:
    at run (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17125:59)
    at Object.<anonymous> (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17150:16)
    at Object.200 (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:17151:30)
    at __webpack_require__ (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:20:30)
    at Object.319 (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:25458:18)
    at __webpack_require__ (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:20:30)
    at 0.module.exports.ctor.super_ (http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:66:18)
    at http://localhost:3000/app.82b63baaa8c4c56f5533.bundle.js:69:10
```

I am working out of the latest skeleton (ESNext + Webpack).  I cannot create a gist because of my view and viewmodel directories.

Note:  I also tried using the `ViewLocator`.  I put this in my main.js file right above `aurelia.use`
```
  ViewLocator.prototype.convertOriginToViewUrl = (origin) => {
    let moduleId = origin.moduleId;
    let id = moduleId.endsWith('.js') ? moduleId.substring(0, moduleId.length - 3) : moduleId;
    return `${id.replace('viewmodels', 'views')}.html`;
  };
```

I also tried using `getViewStrategy` and I always get the same error, `Unable to find module with ID`

**Expected/desired behavior:**
When using the `@useView` decorator on the viewmodel, the corresponding view should be found.

**Comment by EisenbergEffect** [comment]
@jods4 Can you provide some guidance here?

**Comment by jods4** [comment]
Assuming your webpack config includes `modules: ['src', 'node_modules']` and if I understood your structure correctly, I don't see why `@useView(PLATFORM.moduleName('views/app.html')` wouldn't work.

If you're consistent about where you put your views, yes it would be easier to configure Aurelia's default convention to fit your setup. Doing so requires tweaking the convention at runtime _and_ build time:
- at build time option `viewExtensions` is used to find views: [docs](https://github.com/jods4/aurelia-webpack-build/wiki/AureliaPlugin-options#viewfor-and-viewextensions).
- at runtime this is handled by `convertOriginToViewUrl`.

**Comment by jdemeuse1204** [comment]
@jods4 Yes, my webpack does include `modules: ['src', 'node_modules']`.  I am not sure why this or any other convention doesn't work.  I had this all working with framework version `1.0.8`.  I have created a public repo for you, if you want to check it out and see why this is not working.  Otherwise if you pull down the latest skeleton, you will be able to see this issue as well once you split your views and view models into different folders.  This seems like a bug to me.  

Here is the repo:  https://github.com/jdemeuse1204/aurelia-useView-issue

Thank you for the help!

**Comment by jods4** [comment]
@jdemeuse1204 before I have a look at it, can you try what I suggested above? I see your Home viewmodel is not properly configured.

If it still doesn't work I would be interested in the error + the output of `webpack --display-modules`.

**Comment by jdemeuse1204** [comment]
@jods4 That worked.  I never configured `home.js` because `app.js` was not working.  But it wasn't working because of the `home.js` configuration.  Thank you for the help

**Comment by jdemeuse1204** [comment]
@jods4 @EisenbergEffect Is there any way to make an enhancement to get a more intuitive error?  Technically my error was not in my `app.js` file, yet that's where that's where the error was being thrown from

**Comment by jods4** [comment]
Are you sure you didn't dismiss the error too quickly because the message was similar?
I'm pretty sure after you fixed app.html the message should have changed to:

> Error: Unable to find module with ID: **views/home.html**

which is probably as specific as it can be.

**Comment by jdemeuse1204** [comment]
@jods4  You are correct, I must have missed the error.  I just tried to recreate what I thought I was seeing and I cannot.  With trying all the different combinations, I must have missed the name because they are so similar.  Thank you for all the help :)
