### ISSUE TITLE
Child routers do not fully initialize the module

### ISSUE THREAD

**Issue by firelizzard18** [aurelia/framework#807]
**I'm submitting a bug report**

* **Library Version:**
1.1.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.7.3

* **NPM Version:**
4.1.2

* **JSPM Version**
0.16.53

* **Browser:**
Tested in Chrome 59

* **Language:**
all

**Current behavior:**
In scenarios with a child router, for the module in question, for that module's view, if `<router-view>` is anywhere besides in a straight-forward DOM location, `NavigationInstruction` will fail in [`_commitChanges()` line 213](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L213).

In scenarios without a child router, for the root module (App), for that module's view, `<router-view>` can be within a more complex context, such as within an element with `if.bind="..."` or as slotted content of a custom element.

**Expected/desired behavior:**
Modules with a view with `<router-view>` within an element with `if.bind="..."` or as slotted content of a custom element will work regardless of whether they are the root module or a (child-)routed child module.

# Failure mode:
Because of the differing pipelines for a root module and a child module, in the former case, the `RouterView` for a `<router-view>` in one of the specified contexts (or other non-simple contexts) is initialized **before** the commit changes pipeline step, whereas in the latter case, the `RouterView`s in question are initialized at the end of the commit changes pipeline step, after the child navigation instruction has been committed. Thus, in a child module's view, if a `<router-view>` is in a non-simple context, its `RouterView` has not registered its slot, and the commit fails.

_For a child module_

* `LoadRouteStep.run()` is called
    * This calls `loadNewRoute()`
    * This calls `loadRoute()`
    * This calls `loadComponent()`
    * This calls `loadRoute()`
    * This calls `CompositionEngine.ensureViewModel()` which creates the module and sets up any simple `RouterView`s.
* `CommitChangesStep.run()` is called
    * This [calls `NavigationInstruction._commitChanges()`](https://github.com/aurelia/router/blob/fbc3c2c762cfe688346d6a899caaf2fb2a2cf59e/src/navigation-instruction.js#L15) on the instruction to the parent router to navigate to the child module.
    * This [iterates over the view port instructions](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L208).
        1. This [processes the parent router view port](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L221)
            * This [creates a view factory](https://github.com/aurelia/templating-router/blob/master/src/router-view.js#L69) and then [creates a controller for the view port](https://github.com/aurelia/templating-router/blob/master/src/router-view.js#L79).
            * The latter executes the view factory, which [queries the view for targets](https://github.com/aurelia/templating/blob/master/src/view-factory.js#L429) and then [executes those targets](https://github.com/aurelia/templating/blob/master/src/view-factory.js#L459)
            * **This does not execute any `<router-view>`s in non-simple locations, because those do not exist in the fragment at this time.**
        2. This [queues `viewPortInstruction.childNavigationInstruction._commitChanges()`](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L222).
            * **This fails at [line 213](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L213) because the `RotuerView` corresponding to the `<router-view>` has not yet been initialized, and thus has not yet registered it's view port.**
    * I played with multiple `<router-view>`s, and it's only later, when the [queued swap](https://github.com/aurelia/router/blob/ac6bf756749e6c280819ca38d62d514604884fa0/src/navigation-instruction.js#L218) occurs that the other `RouterView`s are created
      * The swap triggers `Controller.automate()` which calls `Controller.bind()`, and this ends up instantiating the other `RouterView`s.

_For a root module_

* `Aurelia.setRoot()` is called.
    * This calls`TemplatingEngine.compose()`.
    * This calls`CompositionEngine.compose()`.
    * This calls`CompositionEngine._createControllerAndSwap()` => `Controller.automate()`.
        1. This calls`CompositionEngine.createController()`.
            * This calls `CompositionEngine.ensureViewModel()` which creates the module and sets up any simple `RouterView`s.
        2. This calls `Controller.automate()`.
            * This calls `Controller.bind()`.
            * **This creates the other `RouterView`s**.
* `CommitChangesStep.run()` is called.
    * This does essentially the same as above (for a child module). The difference being, the router view slot has been registered before this.

<details>

**Full stack trace for `CommitChangesStep`** (captured in the child module scenario)

    at eval (eval at _loop (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js), <anonymous>:1:1)
    at _loop (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:354:13)
    at NavigationInstruction._commitChanges (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:372:9)
    at CommitChangesStep.run (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:210:36)
    at next (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:179:20)
    at iterate (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1307:14)
    at inspect (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1278:16)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1296:24)
    at processPotential (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1424:14)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1295:18)
    at iterate (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1299:12)
    at processActivatable (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1310:12)
    at ActivateNextStep.run (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1191:14)
    at next (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:179:20)
    at iterate (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1220:14)
    at processDeactivatable (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1223:12)
    at DeactivatePreviousStep.run (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1179:14)
    at next (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:179:20)
    at iterate (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1307:14)
    at processActivatable (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1310:12)
    at CanActivateNextStep.run (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:1167:14)
    at next (http://localhost:9000/jspm_packages/npm/aurelia-router@1.3.0/aurelia-router.js:179:20)
    at run (http://localhost:9000/jspm_packages/npm/core-js@2.4.1/modules/es6.promise.js:92:24)
    at eval (http://localhost:9000/jspm_packages/npm/core-js@2.4.1/modules/es6.promise.js:109:9)
    at MutationObserver.flush (http://localhost:9000/jspm_packages/npm/core-js@2.4.1/modules/_microtask.js:22:11)

**Comment by firelizzard18** [comment]
While trying to solve #810, I may have solved this issue. Moving `viewPortInstruction.controller.automate()` from `RouterView.swap()` to `RouterView.process()` seems to resolve this (see the comment on #810 for details).

**Comment by EisenbergEffect** [comment]
We don't support dynamically present router-view elements. Prefer using show.bind which simply hides the router-view.

**Comment by firelizzard18** [comment]
I'm not trying to achieve a dynamically present router-view, but when my content is slotted in a custom-element, that's how it works out.
